development:
  host: localhost
  database: subtrackr

test:
  host: localhost
  database: subtrackr_test

# set these environment variables on your prod server
production:
    uri: <%= ENV['MONGOLAB_URI'] %>
 
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
